# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-03 10:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cow',
            name='date_added',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='milk',
            name='milking_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
