# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-03 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0002_auto_20170803_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilkSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milk', models.FloatField()),
                ('amount', models.FloatField()),
                ('date_sold', models.DateField()),
            ],
        ),
    ]
