# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 10:30
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dairy', '0004_auto_20170822_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cattle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('tag_no', models.CharField(max_length=10)),
                ('breed', models.CharField(blank=True, max_length=30)),
                ('sex', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('gotten_through', models.CharField(blank=True, max_length=20)),
                ('stage', models.CharField(blank=True, max_length=20)),
                ('sire', models.CharField(blank=True, max_length=200)),
                ('conception_method', models.CharField(max_length=50)),
                ('date_added', models.DateField(default=datetime.date.today)),
                ('account', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='cow',
            name='account',
        ),
        migrations.AlterField(
            model_name='milk',
            name='cow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dairy.Cattle'),
        ),
        migrations.DeleteModel(
            name='Cow',
        ),
    ]
