# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 03:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dairy', '0007_cattle_dam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mortality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=200)),
                ('postmortem_report', models.TextField()),
                ('died_on', models.DateField()),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cattle',
            name='cattle_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mortality',
            name='cattle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dairy.Cattle'),
        ),
    ]
