# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 04:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dairy', '0008_auto_20171018_0356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cattle_sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('sold_to', models.CharField(max_length=200)),
                ('date_sold', models.DateField()),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cattle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dairy.Cattle')),
            ],
        ),
    ]
