# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 06:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dairy', '0009_cattle_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed_consumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('feeding_date', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cattle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dairy.Cattle')),
            ],
        ),
        migrations.CreateModel(
            name='Feeds_inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed', models.CharField(max_length=200)),
                ('feed_type', models.CharField(max_length=200)),
                ('stock', models.FloatField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(null=True)),
                ('account', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='feed_consumption',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeds.Feeds_inventory'),
        ),
    ]
